Changes to be committed.
app/views/admin/student.erb line 19.

<td><%= @student.turned_in_assignment?(a) %></td>

NameError at /students/1
undefined local variable or method `assignment_object' for #<Student id: 1, name: "Diana Mkrtchyan"> Did you mean? assignments