When we click on a student, i.e. student #2, we get the following...
NoMethodError at /students/2
undefined method `turned_in_assignment?' for #

Using CMD/Shift/F we know that 'turned_in_assignment' is a method in app/models/student.rb:

/Users/bradleybiehl/Code/02-08-debugging/web-toy__debugging-challenge/app/models/student.rb:
   67    end
   68
   69:   def turned_in_assignment?(assignment_object)
   70      self.grade_for_assignment(assignment_object) != 0
   71    end

  method for turned_in_assignment falls inside class Student
------
In file app/view/admin/student.erb line 19.
Ruby doesn't know what method to call because we don't have the Class specified.

/Users/bradleybiehl/Code/02-08-debugging/web-toy__debugging-challenge/app/views/admin/student.erb:
   17        <tr>
   18          <td><a href="/assignments/<%= a.id %>"><%= a.title %></a></td>
   19:         <td><%= turned_in_assignment? %></td>
   20
   21          <!-- The score and adjusted scores aren't here at all. -->

But now we know this method falls inside class Student
-------
From app/controllers/admin_controller we know class Student is being pulled into app/views/admin/student.erb via @student

MyApp.get "/students/:student_id" do
  @student = Student.find(params[:student_id])
  @assignments = Assignment.all
  erb :"/admin/student"
end
-------
So we did the following TIAS

/Users/bradleybiehl/Code/02-08-debugging/web-toy__debugging-challenge/app/views/admin/student.erb in block (2 levels) in singleton class
        <td><%= turned_in_assignment? %></td>
        <td><%= @student.turned_in_assignment? %></td>

Result: is new error message..
ArgumentError at /students/1
wrong number of arguments (given 0, expected 1)
file: student.rb location: turned_in_assignment? line: 69